apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hrms-pvc
  namespace: storage
spec:
  storageClassName: gp3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi