apiVersion: apps/v1
kind: Deployment

metadata:
  name: hrms-app
  namespace: resources

spec:
  replicas: 1

  selector:
    matchLabels:
      app: hrms

  template:
    metadata:
      labels:
        app: hrms

    spec:
      containers:
      - name: hrms

        image: polinux/stress

        resources:

          requests:
            cpu: "10m"
            memory: "8Mi"

          limits:
            cpu: "1"
            memory: "10Mi"

        command:
        - stress

        args:
        - --vm
        - "1"
        - --vm-bytes
        - "5M"
        - --vm-hang
        - "1"