apiVersion: apps/v1
kind: Deployment

metadata:
  name: hrms-app
  namespace: resources

spec:
  replicas: 1

  selector:
    matchLabels:
      app: hrms

  template:
    metadata:
      labels:
        app: hrms

    spec:
      containers:

      - name: hrms

        image: nginx:1.27

        ports:
        - containerPort: 80

        resources:

          requests:
            cpu: "4000m"
            memory: "512Mi"