apiVersion: v1
kind: ConfigMap

metadata:
  name: hrms-config
  namespace: hrms-volume

data:
  application.properties: |
    app.name=HRMS
    app.env=Production
    db.host=mysql-secondary
    db.port=3306