apiVersion: v1
kind: Secret

metadata:
  name: hrms-secret
  namespace: hrms-volume

type: Opaque

data:
  db-username: aHJhZG1pbg==
  db-password: UGFzc3dvcmRAMTIz
  jwt-secret: and0LXNlY3JldC0xMjM0NTY=