apiVersion: apps/v1
kind: Deployment

metadata:
  name: blue-app
  namespace: deployments

spec:
  replicas: 3

  selector:
    matchLabels:
      app: blue

  template:
    metadata:
      labels:
        app: blue
        version: v1

    spec:
      containers:
      - name: nginx
        image: nginx:1.25

        ports:
        - containerPort: 80

        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5