apiVersion: apps/v1
kind: Deployment

metadata:
  name: canary-app
  namespace: deployments

spec:
  replicas: 10

  selector:
    matchLabels:
      app: nginx1
      track: canary

  template:
    metadata:
      labels:
        app: nginx1
        track: canary
        version: v2

    spec:
      containers:
      - name: nginx1
        image: nginx:1.27

        ports:
        - containerPort: 80

        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5