apiVersion: batch/v1
kind: Job

metadata:
  name: db-migration
  namespace: jobs

spec:
  template:
    spec:
      containers:
      - name: migration
        image: busybox:1.36
        command:
        - sh
        - -c
        - |
          echo "Starting database migration..."
          sleep 5
          exit 1

      restartPolicy: Never

  backoffLimit: 3