apiVersion: v1
kind: Pod
metadata:
  name: multi-pod

spec:
  containers:

  - name: nginx
    image: nginx

  - name: busybox
    image: busybox
    command:
      - sh
      - -c
      - sleep 3600

  - name: alpine
    image: alpine
    command:
      - sh
      - -c
      - sleep 3600