apiVersion: v1
kind: Pod

metadata:
  name: app
  namespace: rbac

spec:
  serviceAccountName: app-sa

  containers:
  - name: app
    image: bitnami/kubectl:latest

    command:
    - sleep
    - "3600"