apiVersion: apps/v1
kind: Deployment

metadata:
  name: hrms-app
  namespace: logs-demo

spec:
  replicas: 3

  selector:
    matchLabels:
      app: hrms

  template:
    metadata:
      labels:
        app: hrms

    spec:
      containers:
      - name: hrms
        image: busybox

        command:
        - sh
        - -c

        args:
        - |
          echo "HRMS Login Service Starting..."
          sleep 10

          echo "Connecting to Database..."
          sleep 10

          echo "Database Authentication Failed!"
          sleep 10

          exit 1