apiVersion: apps/v1
kind: DaemonSet

metadata:
  name: node-monitor
  namespace: monitoring

spec:
  selector:
    matchLabels:
      app: node-monitor

  template:
    metadata:
      labels:
        app: node-monitor

    spec:
      nodeSelector:
        kubernetes.io/os: linux

      containers:
      - name: node-monitor
        image: nginx:stable-alpine

        ports:
        - containerPort: 80