apiVersion: apps/v1
kind: DaemonSet

metadata:
  name: node-monitor
  namespace: monitoring

spec:
  selector:
    matchLabels:
      app: node-monitor

  template:
    metadata:
      labels:
        app: node-monitor

    spec:

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - argocd-lab-worker

      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: Exists
        effect: NoSchedule

      containers:
      - name: node-monitor
        image: nginx:stable-alpine

        ports:
        - containerPort: 80